ALTER TABLE "users"
  ADD COLUMN IF NOT EXISTS "failedLoginAttempts" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "lockedUntil" TIMESTAMP(3);

ALTER TABLE "system_settings"
  ADD COLUMN IF NOT EXISTS "brandingAppName" TEXT,
  ADD COLUMN IF NOT EXISTS "brandingLogoUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "brandingPrimaryColor" TEXT,
  ADD COLUMN IF NOT EXISTS "authSessionIdleTimeoutMinutes" INTEGER DEFAULT 30,
  ADD COLUMN IF NOT EXISTS "authMaxFailedLoginAttempts" INTEGER DEFAULT 5,
  ADD COLUMN IF NOT EXISTS "authLockoutMinutes" INTEGER DEFAULT 15,
  ADD COLUMN IF NOT EXISTS "passwordMinLength" INTEGER DEFAULT 8,
  ADD COLUMN IF NOT EXISTS "passwordRequireUppercase" BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS "passwordRequireLowercase" BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS "passwordRequireNumber" BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS "passwordRequireSymbol" BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS "rateAuthLoginLimit" INTEGER DEFAULT 10,
  ADD COLUMN IF NOT EXISTS "rateAuthLoginWindowSeconds" INTEGER DEFAULT 60,
  ADD COLUMN IF NOT EXISTS "ratePublicVerifySessionLimit" INTEGER DEFAULT 5,
  ADD COLUMN IF NOT EXISTS "ratePublicVerifyIpLimit" INTEGER DEFAULT 20,
  ADD COLUMN IF NOT EXISTS "ratePublicVerifyWindowSeconds" INTEGER DEFAULT 600,
  ADD COLUMN IF NOT EXISTS "ratePublicSubmitSessionLimit" INTEGER DEFAULT 10,
  ADD COLUMN IF NOT EXISTS "ratePublicSubmitIpLimit" INTEGER DEFAULT 20,
  ADD COLUMN IF NOT EXISTS "ratePublicSubmitWindowSeconds" INTEGER DEFAULT 600,
  ADD COLUMN IF NOT EXISTS "rateVerificationCooldownSeconds" INTEGER DEFAULT 60,
  ADD COLUMN IF NOT EXISTS "retentionAutoCleanupEnabled" BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS "retentionResponsesDays" INTEGER,
  ADD COLUMN IF NOT EXISTS "retentionAuditLogsDays" INTEGER DEFAULT 180,
  ADD COLUMN IF NOT EXISTS "retentionInvitationsDays" INTEGER DEFAULT 90,
  ADD COLUMN IF NOT EXISTS "retentionCleanupIntervalHours" INTEGER DEFAULT 24,
  ADD COLUMN IF NOT EXISTS "retentionLastCleanupAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "backupAutoEnabled" BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS "backupIntervalHours" INTEGER DEFAULT 24,
  ADD COLUMN IF NOT EXISTS "backupRetentionDays" INTEGER DEFAULT 14,
  ADD COLUMN IF NOT EXISTS "backupDirectory" TEXT,
  ADD COLUMN IF NOT EXISTS "backupLastRunAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "backupLastStatus" TEXT,
  ADD COLUMN IF NOT EXISTS "backupLastFile" TEXT,
  ADD COLUMN IF NOT EXISTS "backupLastError" TEXT;

UPDATE "system_settings"
SET
  "authSessionIdleTimeoutMinutes" = COALESCE("authSessionIdleTimeoutMinutes", 30),
  "authMaxFailedLoginAttempts" = COALESCE("authMaxFailedLoginAttempts", 5),
  "authLockoutMinutes" = COALESCE("authLockoutMinutes", 15),
  "passwordMinLength" = COALESCE("passwordMinLength", 8),
  "passwordRequireUppercase" = COALESCE("passwordRequireUppercase", true),
  "passwordRequireLowercase" = COALESCE("passwordRequireLowercase", true),
  "passwordRequireNumber" = COALESCE("passwordRequireNumber", true),
  "passwordRequireSymbol" = COALESCE("passwordRequireSymbol", false),
  "rateAuthLoginLimit" = COALESCE("rateAuthLoginLimit", 10),
  "rateAuthLoginWindowSeconds" = COALESCE("rateAuthLoginWindowSeconds", 60),
  "ratePublicVerifySessionLimit" = COALESCE("ratePublicVerifySessionLimit", 5),
  "ratePublicVerifyIpLimit" = COALESCE("ratePublicVerifyIpLimit", 20),
  "ratePublicVerifyWindowSeconds" = COALESCE("ratePublicVerifyWindowSeconds", 600),
  "ratePublicSubmitSessionLimit" = COALESCE("ratePublicSubmitSessionLimit", 10),
  "ratePublicSubmitIpLimit" = COALESCE("ratePublicSubmitIpLimit", 20),
  "ratePublicSubmitWindowSeconds" = COALESCE("ratePublicSubmitWindowSeconds", 600),
  "rateVerificationCooldownSeconds" = COALESCE("rateVerificationCooldownSeconds", 60),
  "retentionAutoCleanupEnabled" = COALESCE("retentionAutoCleanupEnabled", false),
  "retentionAuditLogsDays" = COALESCE("retentionAuditLogsDays", 180),
  "retentionInvitationsDays" = COALESCE("retentionInvitationsDays", 90),
  "retentionCleanupIntervalHours" = COALESCE("retentionCleanupIntervalHours", 24),
  "backupAutoEnabled" = COALESCE("backupAutoEnabled", false),
  "backupIntervalHours" = COALESCE("backupIntervalHours", 24),
  "backupRetentionDays" = COALESCE("backupRetentionDays", 14);

ALTER TABLE "system_settings"
  ALTER COLUMN "authSessionIdleTimeoutMinutes" SET DEFAULT 30,
  ALTER COLUMN "authSessionIdleTimeoutMinutes" SET NOT NULL,
  ALTER COLUMN "authMaxFailedLoginAttempts" SET DEFAULT 5,
  ALTER COLUMN "authMaxFailedLoginAttempts" SET NOT NULL,
  ALTER COLUMN "authLockoutMinutes" SET DEFAULT 15,
  ALTER COLUMN "authLockoutMinutes" SET NOT NULL,
  ALTER COLUMN "passwordMinLength" SET DEFAULT 8,
  ALTER COLUMN "passwordMinLength" SET NOT NULL,
  ALTER COLUMN "passwordRequireUppercase" SET DEFAULT true,
  ALTER COLUMN "passwordRequireUppercase" SET NOT NULL,
  ALTER COLUMN "passwordRequireLowercase" SET DEFAULT true,
  ALTER COLUMN "passwordRequireLowercase" SET NOT NULL,
  ALTER COLUMN "passwordRequireNumber" SET DEFAULT true,
  ALTER COLUMN "passwordRequireNumber" SET NOT NULL,
  ALTER COLUMN "passwordRequireSymbol" SET DEFAULT false,
  ALTER COLUMN "passwordRequireSymbol" SET NOT NULL,
  ALTER COLUMN "rateAuthLoginLimit" SET DEFAULT 10,
  ALTER COLUMN "rateAuthLoginLimit" SET NOT NULL,
  ALTER COLUMN "rateAuthLoginWindowSeconds" SET DEFAULT 60,
  ALTER COLUMN "rateAuthLoginWindowSeconds" SET NOT NULL,
  ALTER COLUMN "ratePublicVerifySessionLimit" SET DEFAULT 5,
  ALTER COLUMN "ratePublicVerifySessionLimit" SET NOT NULL,
  ALTER COLUMN "ratePublicVerifyIpLimit" SET DEFAULT 20,
  ALTER COLUMN "ratePublicVerifyIpLimit" SET NOT NULL,
  ALTER COLUMN "ratePublicVerifyWindowSeconds" SET DEFAULT 600,
  ALTER COLUMN "ratePublicVerifyWindowSeconds" SET NOT NULL,
  ALTER COLUMN "ratePublicSubmitSessionLimit" SET DEFAULT 10,
  ALTER COLUMN "ratePublicSubmitSessionLimit" SET NOT NULL,
  ALTER COLUMN "ratePublicSubmitIpLimit" SET DEFAULT 20,
  ALTER COLUMN "ratePublicSubmitIpLimit" SET NOT NULL,
  ALTER COLUMN "ratePublicSubmitWindowSeconds" SET DEFAULT 600,
  ALTER COLUMN "ratePublicSubmitWindowSeconds" SET NOT NULL,
  ALTER COLUMN "rateVerificationCooldownSeconds" SET DEFAULT 60,
  ALTER COLUMN "rateVerificationCooldownSeconds" SET NOT NULL,
  ALTER COLUMN "retentionAutoCleanupEnabled" SET DEFAULT false,
  ALTER COLUMN "retentionAutoCleanupEnabled" SET NOT NULL,
  ALTER COLUMN "retentionAuditLogsDays" SET DEFAULT 180,
  ALTER COLUMN "retentionAuditLogsDays" SET NOT NULL,
  ALTER COLUMN "retentionInvitationsDays" SET DEFAULT 90,
  ALTER COLUMN "retentionInvitationsDays" SET NOT NULL,
  ALTER COLUMN "retentionCleanupIntervalHours" SET DEFAULT 24,
  ALTER COLUMN "retentionCleanupIntervalHours" SET NOT NULL,
  ALTER COLUMN "backupAutoEnabled" SET DEFAULT false,
  ALTER COLUMN "backupAutoEnabled" SET NOT NULL,
  ALTER COLUMN "backupIntervalHours" SET DEFAULT 24,
  ALTER COLUMN "backupIntervalHours" SET NOT NULL,
  ALTER COLUMN "backupRetentionDays" SET DEFAULT 14,
  ALTER COLUMN "backupRetentionDays" SET NOT NULL;
